"""
Database Schemas

Define your MongoDB collection schemas here using Pydantic models.
These schemas are used for data validation in your application.

Each Pydantic model represents a collection in your database.
Model name is converted to lowercase for the collection name:
- User -> "user" collection
- Product -> "product" collection
- BlogPost -> "blogs" collection
"""

from pydantic import BaseModel, Field, AnyHttpUrl
from typing import Optional

# Example schemas (you can ignore these if not needed by your app):

class User(BaseModel):
    """
    Users collection schema
    Collection name: "user" (lowercase of class name)
    """
    name: str = Field(..., description="Full name")
    email: str = Field(..., description="Email address")
    address: str = Field(..., description="Address")
    age: Optional[int] = Field(None, ge=0, le=120, description="Age in years")
    is_active: bool = Field(True, description="Whether user is active")

class Product(BaseModel):
    """
    Products collection schema
    Collection name: "product" (lowercase of class name)
    """
    title: str = Field(..., description="Product title")
    description: Optional[str] = Field(None, description="Product description")
    price: float = Field(..., ge=0, description="Price in dollars")
    category: str = Field(..., description="Product category")
    in_stock: bool = Field(True, description="Whether product is in stock")

# App-specific schemas
# --------------------------------------------------

class Run(BaseModel):
    """
    Each live update execution.
    Collection name: "run"
    """
    athlete_url: AnyHttpUrl = Field(..., description="Swimrankings athlete profile URL")
    sheet_url: AnyHttpUrl = Field(..., description="Google Sheets document URL")
    sheet_tab: str = Field(..., min_length=1, description="Target sheet tab name")
    ok: bool = Field(..., description="Whether the run completed successfully")
    message: str = Field(..., description="Human readable status message")
    updated_count: int = Field(..., ge=0, description="Number of rows updated in this run")

class Result(BaseModel):
    """
    Updated rows generated by a run.
    Collection name: "result"
    """
    run_id: str = Field(..., description="Reference to the run document id")
    row_number: int
    event: str
    date: str
    old_time: Optional[str] = None
    new_time: str
    delta: Optional[str] = None
